Repository aimemalaika/catalog-ruby, pull requests merged in 2022-04, with the labels that each got.

#32 Feature/item class setup
  app.rb
  classes/item.rb
  main.rb
Labels: enhancement

#33 Feature/classes and methods
  .gitignore
  Gemfile
  Gemfile.lock
  classes/author.rb
  classes/game.rb
  classes/item.rb
Labels: enhancement

#35 Feature/book and label classes
  Gemfile
  Gemfile.lock
  classes/book.rb
  classes/item.rb
  classes/label.rb
  spec/book_spec.rb
  spec/label_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#37 Feature/book move to archive
  classes/book.rb
  spec/book_spec.rb
Labels: enhancement

#42 Add unit tests for all implemented methods.
  classes/item.rb
  spec/author_spec.rb
  spec/game_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#45 Feature/app options book label
  app.rb
  inputs/sanchito_inputs.rb
  modules/book_module.rb
  modules/label_module.rb
Labels: enhancement

#48 IMPLEMENT Book AND Label SQL SCHEMA
  schemas/book_label_schema.sql
Labels: documentation

#50 Feature/store_games
  app.rb
  store/game_read.rb
  store/game_store.rb
Labels: enhancement

#51 Add schema
  schemas/schema.sql
Labels: enhancement

#46 Feature/preserve books labels
  .gitignore
  app.rb
  inputs/new_book_input.rb
  inputs/sanchito_inputs.rb
  main.rb
  modules/book_module.rb
  modules/label_module.rb
  store/books.json
  store/labels.json
  store/load_books.rb
  store/load_labels.rb
  store/store_books.rb
  store/store_labels.rb
Labels: enhancement

#56 MOVE json FILES FOR Book AND Label TO data FOLDER
  app.rb
  data/books.json
  data/labels.json
Labels: enhancement

#52 Catalogue of my Things - Release 1.0
  .gitignore
  Gemfile
  Gemfile.lock
  MIT.md
  README.md
  app.rb
  classes/albums.rb
  classes/author.rb
  classes/book.rb
  classes/game.rb
  classes/genre.rb
  classes/item.rb
  classes/label.rb
  data/albums.json
  data/books.json
  data/games.json
  data/genre.json
  data/labels.json
  database/schema.sql
  inputs/inputs.rb
  inputs/new_book_input.rb
  main.rb
  modules/author_module.rb
  modules/book_module.rb
  modules/label_module.rb
  modules/list_album.rb
  modules/list_genre.rb
  screenshot.png
  spec/album_spec.rb
  spec/author_spec.rb
  spec/book_spec.rb
  spec/game_spec.rb
  spec/genre_spec.rb
  spec/label_spec.rb
  spec/spec_helper.rb
  store/game_read.rb
  store/game_store.rb
  store/load_books.rb
  store/load_labels.rb
  store/store_books.rb
  store/store_labels.rb
Labels: documentation, enhancement
